### ISSUE TITLE
brunch build fails on new project

### ISSUE THREAD

**Issue by losinggeneration** [sandy98/brunch-with-wisp#1]
```
~ $ brunch new https://github.com/sandy98/brunch-with-wisp wisp
07 Oct 14:55:10 - log: Cloning git repo "https://github.com/sandy98/brunch-with-wisp" to "wisp"...
07 Oct 14:55:11 - log: Created skeleton directory layout
07 Oct 14:55:11 - log: Installing packages...
css-brunch@1.5.1 node_modules/css-brunch

javascript-brunch@1.5.1 node_modules/javascript-brunch

clean-css-brunch@1.5.1 node_modules/clean-css-brunch
└── clean-css@0.10.2 (commander@1.1.1)

uglify-js-brunch@1.5.1 node_modules/uglify-js-brunch
└── uglify-js@2.2.5 (optimist@0.3.7, source-map@0.1.43)

wisp-brunch@0.0.6 node_modules/wisp-brunch
└── wisp@0.10.0 (base64-encode@1.0.1, commander@2.8.1, escodegen@1.7.0)

~ $ cd wisp
wisp $ brunch build
/usr/local/lib/node_modules/brunch/lib/watch.js:447
          throw new Error("You probably need to execute `npm install` to insta
                ^
Error: You probably need to execute `npm install` to install brunch plugins. Error: Cannot find module 'wisp/lib/engine/node'
  at /usr/local/lib/node_modules/brunch/lib/watch.js:447:17
  at Array.map (native)
  at loadDeps (/usr/local/lib/node_modules/brunch/lib/watch.js:432:8)
  at loadPackages (/usr/local/lib/node_modules/brunch/lib/watch.js:452:13)
  at /usr/local/lib/node_modules/brunch/lib/watch.js:472:17
  at /usr/local/lib/node_modules/brunch/lib/helpers.js:604:12
  at /usr/local/lib/node_modules/brunch/lib/helpers.js:565:16
  at /usr/local/lib/node_modules/brunch/lib/helpers.js:511:12
  at /usr/local/lib/node_modules/brunch/node_modules/read-components/index.js:263:16
  at /usr/local/lib/node_modules/brunch/node_modules/read-components/index.js:72:14
  at FSReqWrap.cb [as oncomplete] (fs.js:226:19)

wisp $
```

**Comment by losinggeneration** [comment]
Err, I think this is a problem with wisp-brunch, not this project. I'm not sure if I should open the issue there since you own both.
